### ISSUE TITLE
How are webhook payloads published to the service bus? 

### ISSUE THREAD

**Issue by garnertb** [microsoft/opensource-management-portal#454]
I see that the "firehose" service reads GitHub webhook payloads from the service bus, however, it is unclear how those payloads should be published to the service bus.  Is that something this codebase supports or is that something that we need to implement ourselves?

**Comment by jeffwilcox** [comment]
Great question. So there are 3 different ways to get through to the "firehose" for eventually consistency to work, + 1 if you don't:

1. In theory, you could point your app's webhooks at the app's `/webhook` endpoint. We've disabled this after having issues with validating webhook signatures due to some company-specific deployment goo. Less resilient since the processing happens on the web backend.
2. Use your own ingestion service or tech or serverless between webhooks and Service Bus. We're using Azure Logic Apps for this, happy to share how we have that configured.
3. Use your own ingestion thing, we again use Logic Apps, to place the payloads into an Azure Storage Queue. This is more cost-effective probably than Service Bus. We're using this for a similar but different app to validate the codepaths.
4. _Slower eventual consistency_: as long as you don't have billions of repos or teams or things, the Conditional Request logic is designed to slowly build up caches of objects over time. So if you visit a list of teams, you may get a cached version, but it will kick-off a background refresh of this data. You may get some rate-limiting, but it'll eventually be OK.

Are you deploying on Azure or a different provider?

**Comment by jeffwilcox** [comment]
Just sharing some from our logic app in the form of screenshots for now...

**Yes this really is the world's most basic logic app**, could probably be a serverless or even super simple ingress app. However we love knowing that logic apps is on the hook for resiliency here.

![logicapp2](https://user-images.githubusercontent.com/427913/198358024-a0919da9-6240-415a-ac02-a80575118bd1.PNG)

**Basic mapping of some headers into message properties**

![logicapp3](https://user-images.githubusercontent.com/427913/198358159-db532407-4e20-4f66-9128-954e574241e8.PNG)

**Incoming things**

![logicapps1](https://user-images.githubusercontent.com/427913/198358274-21f2f86f-f558-4463-8284-c17e835dec32.PNG)

**Comment by garnertb** [comment]
Thanks for the quick reply! The notes and screenshots are very helpful.  I've gotten everything set up except for the properties mappings which look like they are required as I get this error when consuming webhooks from the queue: `Error: Missing event properties - delivery, signature, and/or event`.  Could you provide the configuration for the send message properties in the screenshot?

**Comment by garnertb** [comment]
Initially getting past this with the configuration below.  Still working through the codebase to understand which of the other properties are required.   Also note, a webhook secret must be set on the GitHub app side for the signature properties to exist on the incoming payload.  

```json
"Properties": {
    "delivery": "@coalesce(triggerOutputs()['headers']['X-GitHub-Delivery'])",
    "event": "@coalesce(triggerOutputs()['headers']['X-GitHub-Event'])",
    "signature": "@coalesce(triggerOutputs()['headers']['X-Hub-Signature'])"
}
```
